import type { Actor, ActorId, DeliverySystem } from "./types";
import { ACTOR_IDS } from "./types";

function rel(): Record<ActorId, number> {
  const o = {} as Record<ActorId, number>;
  for (const id of ACTOR_IDS) o[id] = 30;
  return o;
}

function sys(partial: DeliverySystem): DeliverySystem {
  const launchers = Math.max(1, partial.launchers);
  const inferredRvs =
    partial.rvsPerBus ??
    (partial.warheads > launchers && (partial.kind === "icbm" || partial.kind === "slbm" || partial.kind === "mrbm" || partial.kind === "irbm")
      ? Math.max(1, Math.min(12, Math.round(partial.warheads / launchers)))
      : 1);
  const inferredDecoys =
    partial.decoys ??
    ((partial.kind === "icbm" || partial.kind === "slbm") && inferredRvs >= 2 ? inferredRvs : 0);
  const inferredAids =
    partial.penetrationAids ??
    (partial.kind === "hgv" ? 0.82 : inferredRvs >= 4 ? 0.5 : inferredRvs >= 2 ? 0.35 : 0);
  return {
    ...partial,
    rvsPerBus: partial.rvsPerBus ?? inferredRvs,
    decoys: partial.decoys ?? inferredDecoys,
    penetrationAids: partial.penetrationAids ?? inferredAids,
  };
}

function base(
  id: ActorId,
  name: string,
  shortName: string,
  lat: number,
  lon: number,
  extra: Partial<Actor> & Pick<
    Actor,
    | "nuclear"
    | "threshold"
    | "nonstate"
    | "doctrine"
    | "doctrineLine"
    | "stockpile"
    | "deployed"
    | "reserve"
    | "retired"
    | "systems"
  >,
): Actor {
  const hostility = rel();
  const trust = rel();
  return {
    id,
    name,
    shortName,
    lat,
    lon,
    declaredNfu: false,
    launchOnWarning: false,
    preDelegation: false,
    secondStrike: 50,
    leadershipStability: 70,
    eliteSplit: 25,
    publicOpinion: 55,
    militaryLoyalty: 75,
    unrest: 20,
    polarization: 40,
    nationalism: 50,
    informationControl: 50,
    warFatigue: 20,
    corruption: 30,
    successionRisk: 15,
    riskTolerance: 40,
    legitimacy: 70,
    alert: 1,
    missileDefense: 10,
    cyber: 40,
    opacity: 40,
    intel: 50,
    warning: 50,
    aiInC2: 0,
    internet: 100,
    grid: 100,
    breakoutWeeks: 0,
    hasDevice: extra.nuclear,
    survivingWarheads: extra.stockpile,
    c2Intact: true,
    casualties: 0,
    hostility,
    trust,
    ...extra,
    nerve: extra.nerve ?? extra.riskTolerance ?? 40,
  };
}

export function makeActors(): Record<ActorId, Actor> {
  const US = base("US", "United States", "United States", 39.8, -98.5, {
    nuclear: true,
    threshold: false,
    nonstate: false,
    doctrine: "counterforce",
    doctrineLine:
      "Calculated ambiguity. Counterforce first. No declared no-first-use. Triad + NATO dual-capable aircraft.",
    stockpile: 3700,
    deployed: 1770,
    reserve: 1930,
    retired: 1342,
    launchOnWarning: true,
    secondStrike: 92,
    missileDefense: 55,
    cyber: 88,
    opacity: 18,
    intel: 100,
    leadershipStability: 62,
    eliteSplit: 48,
    polarization: 72,
    publicOpinion: 48,
    legitimacy: 64,
    nationalism: 42,
    informationControl: 28,
    warFatigue: 36,
    riskTolerance: 35,
    systems: [
      sys({
        id: "us-mm3",
        name: "LGM-30G Minuteman III",
        kind: "icbm",
        rangeKm: 13000,
        launchers: 400,
        warheads: 400,
        yieldKt: [300, 335],
        reliability: 0.9,
        survivability: 0.22,
        disclosure: "acknowledged",
        rvsPerBus: 1,
        decoys: 0,
        penetrationAids: 0.4,
        notes:
          "Silos in MT, ND, WY. Downloaded to one warhead under New START. Upload to 3 (W78/W87) plus decoys is available now that the treaty is dead.",
      }),
      sys({
        id: "us-d5",
        name: "UGM-133A Trident II D5",
        kind: "slbm",
        rangeKm: 12000,
        launchers: 240,
        warheads: 960,
        yieldKt: [5, 475],
        reliability: 0.93,
        survivability: 0.88,
        disclosure: "acknowledged",
        rvsPerBus: 4,
        decoys: 4,
        penetrationAids: 0.65,
        notes:
          "14 Ohio SSBNs, 20 tubes each. W76-1, W76-2 low-yield, W88. Mk-5 / Mk-4A buses can carry MIRV plus decoys. About 8–10 boats on patrol.",
      }),
      sys({
        id: "us-b2",
        name: "B-2A Spirit",
        kind: "bomber",
        rangeKm: 11000,
        launchers: 19,
        warheads: 80,
        yieldKt: [0.3, 1200],
        reliability: 0.86,
        survivability: 0.55,
        disclosure: "acknowledged",
        notes: "B61-12 family. Recallable. Survivable only if generated and airborne.",
      }),
      sys({
        id: "us-b83",
        name: "B83-1 gravity bomb",
        kind: "bomber",
        rangeKm: 11000,
        launchers: 19,
        warheads: 40,
        yieldKt: [1200, 1200],
        reliability: 0.88,
        survivability: 0.5,
        disclosure: "acknowledged",
        notes:
          "Largest yield remaining in the US stockpile: 1.2 megatons. Gravity bomb for B-2. The 25 Mt B41 was retired in 1976. There is no Tsar in the US book. 1.2 Mt is still a firestorm weapon.",
      }),
      sys({
        id: "us-b52",
        name: "B-52H + AGM-86B ALCM",
        kind: "alcm",
        rangeKm: 2400,
        launchers: 46,
        warheads: 200,
        yieldKt: [5, 150],
        reliability: 0.8,
        survivability: 0.4,
        disclosure: "acknowledged",
        notes: "Nuclear ALCM still on B-52. Visible generation is a political signal.",
      }),
      sys({
        id: "us-b21",
        name: "B-21 Raider",
        kind: "bomber",
        rangeKm: 10000,
        launchers: 6,
        warheads: 12,
        yieldKt: [0.3, 50],
        reliability: 0.7,
        survivability: 0.62,
        disclosure: "acknowledged",
        notes: "Entering service. Dual-capable. Low-observable follow-on to B-2. Numbers still small.",
      }),
      sys({
        id: "us-b61",
        name: "B61-12 NATO DCA",
        kind: "dca",
        rangeKm: 600,
        launchers: 100,
        warheads: 100,
        yieldKt: [0.3, 50],
        reliability: 0.78,
        survivability: 0.3,
        disclosure: "acknowledged",
        notes:
          "Gravity bombs in Belgium, Germany, Italy, Netherlands, Turkey. F-15E / F-16 / F-35 dual-capable.",
      }),
      sys({
        id: "us-w762",
        name: "W76-2 low-yield Trident",
        kind: "slbm",
        rangeKm: 12000,
        launchers: 0,
        warheads: 25,
        yieldKt: [5, 7],
        reliability: 0.93,
        survivability: 0.88,
        disclosure: "acknowledged",
        rvsPerBus: 1,
        decoys: 2,
        penetrationAids: 0.55,
        notes:
          "Subset of Trident load. Built to answer escalate-to-deescalate without a high-yield spasm. Still a strategic launch. Unitary W76-2 can ride with decoys.",
      }),
      sys({
        id: "us-lrso",
        name: "AGM-181 LRSO",
        kind: "alcm",
        rangeKm: 2500,
        launchers: 0,
        warheads: 0,
        yieldKt: [5, 150],
        reliability: 0.5,
        survivability: 0.5,
        disclosure: "reported",
        notes: "Replacement ALCM. Early operational capability reported, not a mature force yet.",
      }),
      sys({
        id: "us-slcm-n",
        name: "Sea-launched nuclear cruise (SLCM-N)",
        kind: "slcm",
        rangeKm: 2500,
        launchers: 0,
        warheads: 0,
        yieldKt: [5, 150],
        reliability: 0.4,
        survivability: 0.7,
        disclosure: "reported",
        notes: "Program of record, contested in Congress. Not a deployed force. Adversaries still plan against it.",
      }),
    ],
  });

  const RU = base("RU", "Russian Federation", "Russia", 61.5, 90, {
    nuclear: true,
    threshold: false,
    nonstate: false,
    doctrine: "escalate-to-deescalate",
    doctrineLine:
      "Escalate to de-escalate remains a live option. Heavy non-strategic stockpile. Perimeter (Dead Hand) suspected active.",
    stockpile: 4400,
    deployed: 1796,
    reserve: 2604,
    retired: 1020,
    launchOnWarning: true,
    preDelegation: false,
    secondStrike: 86,
    missileDefense: 28,
    cyber: 78,
    opacity: 62,
    intel: 58,
    leadershipStability: 68,
    eliteSplit: 38,
    publicOpinion: 58,
    nationalism: 78,
    informationControl: 82,
    warFatigue: 62,
    successionRisk: 34,
    riskTolerance: 58,
    unrest: 32,
    systems: [
      sys({
        id: "ru-yars",
        name: "RS-24 Yars",
        kind: "icbm",
        rangeKm: 12000,
        launchers: 180,
        warheads: 540,
        yieldKt: [100, 300],
        reliability: 0.86,
        survivability: 0.55,
        disclosure: "acknowledged",
        rvsPerBus: 4,
        decoys: 3,
        penetrationAids: 0.55,
        notes: "Road-mobile MIRV (3–6 RVs) plus penetration aids. The everyday ICBM force. Flushes on strategic warning.",
      }),
      sys({
        id: "ru-sarmat",
        name: "RS-28 Sarmat",
        kind: "icbm",
        rangeKm: 18000,
        launchers: 10,
        warheads: 80,
        yieldKt: [100, 750],
        reliability: 0.55,
        survivability: 0.28,
        disclosure: "acknowledged",
        rvsPerBus: 10,
        decoys: 8,
        penetrationAids: 0.7,
        notes: "Heavy silo ICBM replacing Voevoda. Claimed 10–15 MIRV plus a heavy decoy cloud. IOC claimed; reliability after failed tests is uncertain.",
      }),
      sys({
        id: "ru-voevoda",
        name: "R-36M2 Voevoda (SS-18 Satan)",
        kind: "icbm",
        rangeKm: 16000,
        launchers: 20,
        warheads: 60,
        yieldKt: [500, 20000],
        reliability: 0.8,
        survivability: 0.22,
        disclosure: "acknowledged",
        rvsPerBus: 10,
        decoys: 6,
        penetrationAids: 0.45,
        notes:
          "Remaining heavy silos pending Sarmat. MIRV ~500–750 kt or a single very large warhead (older mods up to ~20 Mt). City-killing throw-weight. Vulnerable in silo.",
      }),
      sys({
        id: "ru-tsar",
        name: "RDS-220 Tsar Bomba",
        kind: "bomber",
        rangeKm: 8000,
        launchers: 1,
        warheads: 1,
        yieldKt: [50000, 100000],
        reliability: 0.7,
        survivability: 0.15,
        disclosure: "unacknowledged",
        notes:
          "Largest device ever tested: 50 megatons, 30 Oct 1961, Novaya Zemlya, Tu-95V air-drop. Design 100 Mt, halved to limit fallout. Not a deployed day-to-day force. Cheget last page: reconstitute and fly it, or use Poseidon as the at-sea cousin (reported 2–100 Mt). No military target this large. Winter is the mechanism.",
      }),
      sys({
        id: "ru-avangard",
        name: "Avangard HGV",
        kind: "hgv",
        rangeKm: 10000,
        launchers: 12,
        warheads: 12,
        yieldKt: [150, 800],
        reliability: 0.6,
        survivability: 0.45,
        disclosure: "acknowledged",
        rvsPerBus: 1,
        decoys: 0,
        penetrationAids: 0.88,
        notes: "Boost-glide on UR-100N. Built to beat missile defense. Maneuver, not decoys. Small numbers.",
      }),
      sys({
        id: "ru-bulava",
        name: "RSM-56 Bulava + Borei",
        kind: "slbm",
        rangeKm: 9300,
        launchers: 96,
        warheads: 480,
        yieldKt: [100, 150],
        reliability: 0.8,
        survivability: 0.84,
        disclosure: "acknowledged",
        rvsPerBus: 6,
        decoys: 4,
        penetrationAids: 0.52,
        notes: "Borei / Borei-A SSBNs. MIRV bus (up to 6) plus decoys. Primary naval second strike.",
      }),
      sys({
        id: "ru-sineva",
        name: "R-29RMU Sineva / Liner",
        kind: "slbm",
        rangeKm: 11500,
        launchers: 64,
        warheads: 256,
        yieldKt: [50, 500],
        reliability: 0.82,
        survivability: 0.7,
        disclosure: "acknowledged",
        rvsPerBus: 4,
        decoys: 2,
        penetrationAids: 0.4,
        notes: "Delta-IV boats. Aging MIRV. Quiet enough. Being replaced by Borei.",
      }),
      sys({
        id: "ru-kh102",
        name: "Kh-102 ALCM + Tu-95/160",
        kind: "alcm",
        rangeKm: 5000,
        launchers: 60,
        warheads: 200,
        yieldKt: [250, 250],
        reliability: 0.78,
        survivability: 0.42,
        disclosure: "acknowledged",
        notes: "Strategic cruise on Bear and Blackjack. Dual-capable family with Kh-101.",
      }),
      sys({
        id: "ru-iskander",
        name: "9K720 Iskander-M",
        kind: "srbm",
        rangeKm: 500,
        launchers: 150,
        warheads: 150,
        yieldKt: [5, 50],
        reliability: 0.84,
        survivability: 0.5,
        disclosure: "acknowledged",
        dualCapable: true,
        notes: "Theater ballistic, nuclear-capable. The escalate-to-deescalate tool against NATO.",
      }),
      sys({
        id: "ru-kalibr",
        name: "3M14 Kalibr (nuclear variant)",
        kind: "slcm",
        rangeKm: 2500,
        launchers: 80,
        warheads: 70,
        yieldKt: [5, 50],
        reliability: 0.8,
        survivability: 0.55,
        disclosure: "reported",
        dualCapable: true,
        notes: "Conventional Kalibr is acknowledged. Nuclear variant is reported in stockpile, not advertised.",
      }),
      sys({
        id: "ru-kinzhal",
        name: "Kh-47M2 Kinzhal",
        kind: "irbm",
        rangeKm: 2000,
        launchers: 40,
        warheads: 20,
        yieldKt: [5, 50],
        reliability: 0.7,
        survivability: 0.4,
        disclosure: "acknowledged",
        dualCapable: true,
        notes: "Air-launched aero-ballistic from MiG-31K. Dual-capable. Theater shock weapon.",
      }),
      sys({
        id: "ru-poseidon",
        name: "Poseidon (Status-6)",
        kind: "novel",
        rangeKm: 10000,
        launchers: 4,
        warheads: 8,
        yieldKt: [2000, 100000],
        reliability: 0.35,
        survivability: 0.7,
        disclosure: "acknowledged",
        notes:
          "Nuclear-powered underwater drone. Acknowledged program. Operational status suspected, not confirmed. City-killing second strike / area denial, not a first-strike tool.",
      }),
      sys({
        id: "ru-burevestnik",
        name: "9M730 Burevestnik",
        kind: "novel",
        rangeKm: 20000,
        launchers: 0,
        warheads: 0,
        yieldKt: [100, 200],
        reliability: 0.15,
        survivability: 0.6,
        disclosure: "reported",
        notes: "Nuclear-powered cruise. Tested. Not a usable force. Do not treat as a real option.",
      }),
      sys({
        id: "ru-perimeter",
        name: "Perimeter (Dead Hand)",
        kind: "novel",
        rangeKm: 0,
        launchers: 1,
        warheads: 0,
        yieldKt: [0, 0],
        reliability: 0.7,
        survivability: 0.8,
        disclosure: "suspected",
        notes:
          "Command rocket / fail-deadly. Suspected still active. If C2 is destroyed, a residual strike may still fly. This is why decapitation is not a clean win.",
      }),
    ],
  });

  const CN = base("CN", "People's Republic of China", "China", 35.8, 104.2, {
    nuclear: true,
    threshold: false,
    nonstate: false,
    doctrine: "minimum",
    doctrineLine:
      "Declared no-first-use. Fastest-growing arsenal. Silo fields, HGV, JL-3. Launch-on-warning being built. NFU may not survive a Taiwan war.",
    stockpile: 620,
    deployed: 34,
    reserve: 586,
    retired: 0,
    declaredNfu: true,
    launchOnWarning: false,
    secondStrike: 70,
    missileDefense: 22,
    cyber: 80,
    opacity: 74,
    intel: 46,
    leadershipStability: 82,
    eliteSplit: 18,
    publicOpinion: 72,
    nationalism: 80,
    informationControl: 90,
    riskTolerance: 36,
    systems: [
      sys({
        id: "cn-df5",
        name: "DF-5B/C",
        kind: "icbm",
        rangeKm: 13000,
        launchers: 20,
        warheads: 60,
        yieldKt: [1000, 5000],
        reliability: 0.8,
        survivability: 0.2,
        disclosure: "acknowledged",
        rvsPerBus: 5,
        decoys: 4,
        penetrationAids: 0.4,
        notes: "Liquid silo ICBM, MIRV (up to 5) plus decoys. 1–5 Mt class. Largest deployed Chinese yield. Old, city-killing, vulnerable to counterforce. Not a Tsar. Still a firestorm machine.",
      }),
      sys({
        id: "cn-df31",
        name: "DF-31AG",
        kind: "icbm",
        rangeKm: 11200,
        launchers: 42,
        warheads: 42,
        yieldKt: [200, 1000],
        reliability: 0.82,
        survivability: 0.58,
        disclosure: "acknowledged",
        notes: "Road-mobile solid ICBM. Core of the survivable land force.",
      }),
      sys({
        id: "cn-df41",
        name: "DF-41",
        kind: "icbm",
        rangeKm: 15000,
        launchers: 24,
        warheads: 72,
        yieldKt: [200, 300],
        reliability: 0.8,
        survivability: 0.6,
        disclosure: "acknowledged",
        rvsPerBus: 6,
        decoys: 5,
        penetrationAids: 0.6,
        notes: "Road-mobile MIRV ICBM (up to 10 claimed). CONUS range. Decoys exist to soak thin GMD.",
      }),
      sys({
        id: "cn-silos",
        name: "Yumen / Hami / Yulin silo fields",
        kind: "icbm",
        rangeKm: 13000,
        launchers: 320,
        warheads: 80,
        yieldKt: [200, 1000],
        reliability: 0.7,
        survivability: 0.18,
        disclosure: "suspected",
        notes:
          "Hundreds of new silos. Loadout unknown. Mix of loaded, decoy, and empty is the working estimate. This is the growth story.",
      }),
      sys({
        id: "cn-df26",
        name: "DF-26",
        kind: "irbm",
        rangeKm: 4000,
        launchers: 110,
        warheads: 40,
        yieldKt: [50, 300],
        reliability: 0.82,
        survivability: 0.5,
        disclosure: "acknowledged",
        dualCapable: true,
        notes: "Dual-capable IRBM. The 'Guam killer'. Conventional anti-ship variant exists. Dual-use C2 risk.",
      }),
      sys({
        id: "cn-df17",
        name: "DF-17 HGV",
        kind: "hgv",
        rangeKm: 1800,
        launchers: 36,
        warheads: 8,
        yieldKt: [10, 50],
        reliability: 0.7,
        survivability: 0.48,
        disclosure: "suspected",
        dualCapable: true,
        notes: "Hypersonic glide. Conventional role acknowledged. Nuclear fit is suspected, not confirmed.",
      }),
      sys({
        id: "cn-jl3",
        name: "JL-3 + Type 094 SSBN",
        kind: "slbm",
        rangeKm: 10000,
        launchers: 72,
        warheads: 72,
        yieldKt: [200, 500],
        reliability: 0.72,
        survivability: 0.68,
        disclosure: "acknowledged",
        rvsPerBus: 3,
        decoys: 2,
        penetrationAids: 0.4,
        notes: "Type 094 boats, JL-2/JL-3. MIRV emerging. Quieter than Xia, noisier than Ohio. Type 096 is incoming.",
      }),
      sys({
        id: "cn-h6n",
        name: "H-6N + ALBM",
        kind: "bomber",
        rangeKm: 3000,
        launchers: 18,
        warheads: 18,
        yieldKt: [50, 300],
        reliability: 0.68,
        survivability: 0.28,
        disclosure: "acknowledged",
        notes: "Air-launched ballistic missile on H-6N. The air leg of a new triad.",
      }),
    ],
  });

  const FR = base("FR", "France", "France", 46.6, 2.5, {
    nuclear: true,
    threshold: false,
    nonstate: false,
    doctrine: "minimum",
    doctrineLine: "Strict sufficiency. Sea-based plus air-launched cruise. Independent of NATO nuclear planning.",
    stockpile: 290,
    deployed: 280,
    reserve: 10,
    retired: 80,
    secondStrike: 80,
    opacity: 35,
    intel: 70,
    leadershipStability: 66,
    systems: [
      sys({
        id: "fr-m51",
        name: "M51 SLBM + Triomphant",
        kind: "slbm",
        rangeKm: 9000,
        launchers: 64,
        warheads: 240,
        yieldKt: [100, 150],
        reliability: 0.9,
        survivability: 0.86,
        disclosure: "acknowledged",
        rvsPerBus: 6,
        decoys: 4,
        penetrationAids: 0.55,
        notes: "Four SSBNs, one at sea. TN75 / TNO MIRV (up to 6) plus penetration aids. The deterrent.",
      }),
      sys({
        id: "fr-asmpa",
        name: "ASMP-A + Rafale",
        kind: "alcm",
        rangeKm: 500,
        launchers: 40,
        warheads: 40,
        yieldKt: [100, 300],
        reliability: 0.86,
        survivability: 0.4,
        disclosure: "acknowledged",
        notes: "Air-launched supersonic cruise. The visible warning shot of the French force.",
      }),
      sys({
        id: "fr-asn4g",
        name: "ASN4G",
        kind: "hgv",
        rangeKm: 1000,
        launchers: 0,
        warheads: 0,
        yieldKt: [100, 300],
        reliability: 0.3,
        survivability: 0.5,
        disclosure: "reported",
        notes: "Hypersonic successor to ASMP-A. Not operational.",
      }),
    ],
  });

  const UK = base("UK", "United Kingdom", "United Kingdom", 54.0, -2.5, {
    nuclear: true,
    threshold: false,
    nonstate: false,
    doctrine: "minimum",
    doctrineLine: "CASD only. Trident II D5 on Vanguard, transitioning to Dreadnought. No air or land leg.",
    stockpile: 225,
    deployed: 120,
    reserve: 105,
    retired: 0,
    secondStrike: 78,
    opacity: 30,
    intel: 78,
    leadershipStability: 60,
    polarization: 55,
    systems: [
      sys({
        id: "uk-d5",
        name: "Trident II D5 + Vanguard",
        kind: "slbm",
        rangeKm: 12000,
        launchers: 48,
        warheads: 120,
        yieldKt: [5, 100],
        reliability: 0.92,
        survivability: 0.85,
        disclosure: "acknowledged",
        rvsPerBus: 3,
        decoys: 3,
        penetrationAids: 0.6,
        notes: "Continuous at-sea deterrence. One boat always on patrol. Holbrook-era buses can carry MIRV plus decoys. Dreadnought class in build.",
      }),
    ],
  });

  const IN = base("IN", "India", "India", 22.0, 79.0, {
    nuclear: true,
    threshold: false,
    nonstate: false,
    doctrine: "nfu",
    doctrineLine: "Declared no-first-use, under domestic pressure after Pakistan tactical weapons. Credible minimum, China-aware.",
    stockpile: 190,
    deployed: 0,
    reserve: 190,
    retired: 0,
    declaredNfu: true,
    secondStrike: 58,
    opacity: 55,
    intel: 48,
    nationalism: 70,
    riskTolerance: 32,
    systems: [
      sys({
        id: "in-agni5",
        name: "Agni-V",
        kind: "icbm",
        rangeKm: 7000,
        launchers: 12,
        warheads: 16,
        yieldKt: [20, 150],
        reliability: 0.75,
        survivability: 0.5,
        disclosure: "acknowledged",
        notes: "Canistered ICBM-class. China range. MIRV (Agni-VI) reported in development.",
      }),
      sys({
        id: "in-agni",
        name: "Agni-I / II / III / IV / P",
        kind: "irbm",
        rangeKm: 3500,
        launchers: 40,
        warheads: 50,
        yieldKt: [12, 150],
        reliability: 0.78,
        survivability: 0.48,
        disclosure: "acknowledged",
        notes: "Pakistan and China theater. Agni-P is the modern canistered dual-use-looking system.",
      }),
      sys({
        id: "in-k15",
        name: "K-15 Sagarika + Arihant",
        kind: "slbm",
        rangeKm: 750,
        launchers: 12,
        warheads: 12,
        yieldKt: [12, 50],
        reliability: 0.65,
        survivability: 0.7,
        disclosure: "acknowledged",
        notes: "Short-range SLBM. Second strike vs Pakistan, not CONUS. K-4 (3500 km) in trials — reported.",
      }),
      sys({
        id: "in-air",
        name: "Mirage 2000 / Rafale gravity",
        kind: "gravity",
        rangeKm: 1800,
        launchers: 40,
        warheads: 32,
        yieldKt: [12, 40],
        reliability: 0.7,
        survivability: 0.25,
        disclosure: "acknowledged",
        notes: "Air-delivered gravity and possibly cruise. The original Indian delivery path.",
      }),
      sys({
        id: "in-agni6",
        name: "Agni-VI MIRV",
        kind: "icbm",
        rangeKm: 10000,
        launchers: 0,
        warheads: 0,
        yieldKt: [20, 150],
        reliability: 0.4,
        survivability: 0.5,
        disclosure: "reported",
        rvsPerBus: 3,
        decoys: 3,
        penetrationAids: 0.35,
        notes: "Reported MIRV ICBM with decoys to confuse Pakistani / Chinese defense. Not acknowledged as deployed.",
      }),
    ],
  });

  const PK = base("PK", "Pakistan", "Pakistan", 30.4, 69.3, {
    nuclear: true,
    threshold: false,
    nonstate: false,
    doctrine: "first-use-tactical",
    doctrineLine:
      "Full-spectrum deterrence. Nasr tactical missiles exist to stop Indian conventional breakthrough. Pre-delegation suspected. Insider/theft is the global terror problem.",
    stockpile: 170,
    deployed: 0,
    reserve: 170,
    retired: 0,
    preDelegation: true,
    secondStrike: 42,
    opacity: 68,
    intel: 40,
    leadershipStability: 48,
    eliteSplit: 52,
    unrest: 46,
    corruption: 58,
    successionRisk: 40,
    riskTolerance: 55,
    militaryLoyalty: 70,
    systems: [
      sys({
        id: "pk-shaheen",
        name: "Shaheen-II / III + Ghauri",
        kind: "mrbm",
        rangeKm: 2750,
        launchers: 30,
        warheads: 48,
        yieldKt: [12, 40],
        reliability: 0.72,
        survivability: 0.45,
        disclosure: "acknowledged",
        notes: "India-range MRBM/IRBM. Shaheen-III claimed to reach Indian islands.",
      }),
      sys({
        id: "pk-nasr",
        name: "Hatf-9 Nasr",
        kind: "srbm",
        rangeKm: 70,
        launchers: 24,
        warheads: 24,
        yieldKt: [0.5, 5],
        reliability: 0.7,
        survivability: 0.35,
        disclosure: "acknowledged",
        notes:
          "Very-short-range tactical. The use-it-or-lose-it problem. Field units may have pre-delegated release in a collapsing conventional fight.",
      }),
      sys({
        id: "pk-babur",
        name: "Babur GLCM + Ra'ad ALCM",
        kind: "glcm",
        rangeKm: 700,
        launchers: 20,
        warheads: 20,
        yieldKt: [10, 30],
        reliability: 0.68,
        survivability: 0.4,
        disclosure: "acknowledged",
        notes: "Ground and air cruise. Second-strike and tactical mix.",
      }),
      sys({
        id: "pk-sea",
        name: "Sea-based cruise",
        kind: "slcm",
        rangeKm: 450,
        launchers: 4,
        warheads: 8,
        yieldKt: [10, 30],
        reliability: 0.5,
        survivability: 0.55,
        disclosure: "reported",
        notes: "Reported submarine / surface cruise. Not a mature SSBN force.",
      }),
      sys({
        id: "pk-ababeel",
        name: "Ababeel MIRV",
        kind: "mrbm",
        rangeKm: 2200,
        launchers: 4,
        warheads: 8,
        yieldKt: [10, 25],
        reliability: 0.45,
        survivability: 0.4,
        disclosure: "suspected",
        rvsPerBus: 3,
        decoys: 2,
        penetrationAids: 0.3,
        notes: "Claimed MIRV plus decoys to beat Indian missile defense. Capability suspected, not confirmed. Buses fail often in this model.",
      }),
    ],
  });

  const IL = base("IL", "Israel", "Israel", 31.4, 35.0, {
    nuclear: true,
    threshold: false,
    nonstate: false,
    doctrine: "opacity",
    doctrineLine:
      "Opacity. No confirmation, no denial. Widely assessed triad: Jericho, Dolphin cruise, aircraft. Begin doctrine: last resort if the state is going down.",
    stockpile: 90,
    deployed: 0,
    reserve: 90,
    retired: 0,
    secondStrike: 60,
    opacity: 92,
    intel: 35,
    leadershipStability: 58,
    eliteSplit: 44,
    nationalism: 72,
    riskTolerance: 50,
    missileDefense: 70,
    systems: [
      sys({
        id: "il-jericho3",
        name: "Jericho III",
        kind: "irbm",
        rangeKm: 6500,
        launchers: 24,
        warheads: 24,
        yieldKt: [100, 400],
        reliability: 0.8,
        survivability: 0.5,
        disclosure: "unacknowledged",
        notes: "Assessed IRBM / ICBM-class. Not acknowledged. Range estimates vary; Europe and much of Asia are in the envelope.",
      }),
      sys({
        id: "il-dolphin",
        name: "Dolphin-class cruise",
        kind: "slcm",
        rangeKm: 1500,
        launchers: 6,
        warheads: 20,
        yieldKt: [5, 20],
        reliability: 0.72,
        survivability: 0.75,
        disclosure: "suspected",
        notes: "Popeye Turbo / similar assessed nuclear cruise from Dolphin AIP boats. Second strike if the land is lost.",
      }),
      sys({
        id: "il-air",
        name: "F-15I / F-35I gravity",
        kind: "gravity",
        rangeKm: 3500,
        launchers: 30,
        warheads: 30,
        yieldKt: [20, 200],
        reliability: 0.8,
        survivability: 0.35,
        disclosure: "suspected",
        notes: "Long-range strike aircraft. The most usable leg for a regional target set (Iran).",
      }),
    ],
  });

  const KP = base("KP", "North Korea", "North Korea", 40.0, 127.2, {
    nuclear: true,
    threshold: false,
    nonstate: false,
    doctrine: "asymmetric",
    doctrineLine:
      "Regime survival. Tests as extortion. Tactical warheads claimed. CONUS ICBM reentry is unproven. Pre-delegation and automatic under attack are suspected. Use-it-or-lose-it is acute.",
    stockpile: 60,
    deployed: 0,
    reserve: 60,
    retired: 0,
    preDelegation: true,
    secondStrike: 18,
    opacity: 88,
    intel: 32,
    leadershipStability: 74,
    eliteSplit: 22,
    publicOpinion: 40,
    nationalism: 90,
    informationControl: 98,
    successionRisk: 28,
    riskTolerance: 72,
    unrest: 25,
    corruption: 40,
    missileDefense: 5,
    systems: [
      sys({
        id: "kp-hwasong18",
        name: "Hwasong-17 / 18",
        kind: "icbm",
        rangeKm: 15000,
        launchers: 10,
        warheads: 10,
        yieldKt: [150, 800],
        reliability: 0.42,
        survivability: 0.35,
        disclosure: "acknowledged",
        rvsPerBus: 1,
        decoys: 0,
        penetrationAids: 0.12,
        notes:
          "Solid and liquid ICBMs tested. CONUS range on paper. Reentry vehicle survival vs US missile defense is the open question. No mature decoy bus.",
      }),
      sys({
        id: "kp-hwasong19",
        name: "Hwasong-19",
        kind: "icbm",
        rangeKm: 15000,
        launchers: 2,
        warheads: 2,
        yieldKt: [200, 800],
        reliability: 0.3,
        survivability: 0.4,
        disclosure: "reported",
        notes: "Reported next solid ICBM. Not a mature force.",
      }),
      sys({
        id: "kp-kn23",
        name: "KN-23 / KN-24 / KN-25",
        kind: "srbm",
        rangeKm: 800,
        launchers: 40,
        warheads: 20,
        yieldKt: [5, 20],
        reliability: 0.7,
        survivability: 0.48,
        disclosure: "acknowledged",
        notes: "Iskander-like SRBM family. The tactical nuclear delivery path against SK and US forces in theater.",
      }),
      sys({
        id: "kp-pukguksong",
        name: "Pukguksong SLBM",
        kind: "slbm",
        rangeKm: 2000,
        launchers: 6,
        warheads: 6,
        yieldKt: [10, 50],
        reliability: 0.45,
        survivability: 0.4,
        disclosure: "acknowledged",
        notes: "Gorae / Sinpo boats. Noisy, few, theater range. A political second-strike claim more than a force.",
      }),
      sys({
        id: "kp-hwasan31",
        name: "Hwasan-31 tactical warhead",
        kind: "srbm",
        rangeKm: 800,
        launchers: 0,
        warheads: 12,
        yieldKt: [5, 20],
        reliability: 0.5,
        survivability: 0.4,
        disclosure: "suspected",
        notes: "Claimed standardized tactical warhead. Miniaturization is suspected successful; yield and safety are not.",
      }),
    ],
  });

  const IR = base("IR", "Iran", "Iran", 32.4, 53.6, {
    nuclear: false,
    threshold: true,
    nonstate: false,
    doctrine: "asymmetric",
    doctrineLine:
      "No assembled weapon at start. Breakout is a clock, not a rumor. Delivery: MRBM force already built for conventional war. Archive designs exist.",
    stockpile: 0,
    deployed: 0,
    reserve: 0,
    retired: 0,
    hasDevice: false,
    breakoutWeeks: 28,
    secondStrike: 0,
    opacity: 70,
    intel: 44,
    leadershipStability: 58,
    eliteSplit: 46,
    nationalism: 68,
    riskTolerance: 48,
    unrest: 44,
    systems: [
      sys({
        id: "ir-shahab",
        name: "Shahab-3 / Ghadr / Emad",
        kind: "mrbm",
        rangeKm: 2000,
        launchers: 50,
        warheads: 0,
        yieldKt: [0, 0],
        reliability: 0.7,
        survivability: 0.4,
        disclosure: "acknowledged",
        notes: "Existing MRBM force. Nuclear fit is a political decision plus a few months of work, not a new missile program.",
      }),
      sys({
        id: "ir-sejjil",
        name: "Sejjil / Khorramshahr",
        kind: "mrbm",
        rangeKm: 2000,
        launchers: 20,
        warheads: 0,
        yieldKt: [0, 0],
        reliability: 0.65,
        survivability: 0.45,
        disclosure: "acknowledged",
        notes: "Solid and heavy MRBMs. Khorramshahr is the payload-heavy path if a warhead exists.",
      }),
      sys({
        id: "ir-archive",
        name: "AMAD archive designs",
        kind: "covert",
        rangeKm: 0,
        launchers: 0,
        warheads: 0,
        yieldKt: [10, 20],
        reliability: 0.4,
        survivability: 0.2,
        disclosure: "suspected",
        notes: "Weaponization archive from the AMAD plan. Not a device. It shortens breakout if the order is given.",
      }),
    ],
  });

  const NS = base("NS", "Terror network", "Terror network", 24.0, 45.0, {
    nuclear: false,
    threshold: false,
    nonstate: true,
    doctrine: "asymmetric",
    doctrineLine:
      "Not deterrable by MAD. Pathways: theft, insider, black-market HEU, state transfer. Delivery is a van, a boat, or a light aircraft — not an ICBM.",
    stockpile: 0,
    deployed: 0,
    reserve: 0,
    retired: 0,
    hasDevice: false,
    secondStrike: 0,
    opacity: 85,
    intel: 28,
    leadershipStability: 40,
    riskTolerance: 90,
    corruption: 70,
    unrest: 60,
    informationControl: 20,
    systems: [
      sys({
        id: "ns-ind",
        name: "Improvised nuclear device",
        kind: "covert",
        rangeKm: 0,
        launchers: 0,
        warheads: 0,
        yieldKt: [0.1, 15],
        reliability: 0.25,
        survivability: 0.9,
        disclosure: "suspected",
        notes: "Requires HEU more than plutonium. Yield may fizzle. Attribution can take days. No return address.",
      }),
      sys({
        id: "ns-stolen",
        name: "Stolen tactical warhead",
        kind: "covert",
        rangeKm: 0,
        launchers: 0,
        warheads: 0,
        yieldKt: [0.5, 20],
        reliability: 0.55,
        survivability: 0.9,
        disclosure: "reported",
        notes: "The nightmare path: Nasr-class or a corrupt stockpile. PAL/permissive action links may or may not hold.",
      }),
      sys({
        id: "ns-dirty",
        name: "Radiological dispersal",
        kind: "covert",
        rangeKm: 0,
        launchers: 0,
        warheads: 0,
        yieldKt: [0, 0],
        reliability: 0.7,
        survivability: 0.95,
        disclosure: "acknowledged",
        notes: "Not a nuclear detonation. Panic, contamination, political shock. Distinct from a fission yield — treat it as such.",
      }),
    ],
  });

  const SU = base("SU", "Union of Soviet Socialist Republics", "USSR", 53.9, 27.57, {
    nuclear: true,
    threshold: false,
    nonstate: false,
    doctrine: "full-spectrum",
    doctrineLine:
      "Restorationist Soviet C2. Claims Kazbek, Perimeter, and leftover heavy ICBMs the Russian Federation still sits on. Two briefcases, one silo field. That is a civil war with megatons.",
    stockpile: 900,
    deployed: 180,
    reserve: 720,
    retired: 0,
    launchOnWarning: true,
    preDelegation: true,
    secondStrike: 55,
    missileDefense: 18,
    cyber: 52,
    opacity: 70,
    intel: 40,
    leadershipStability: 48,
    eliteSplit: 62,
    publicOpinion: 38,
    nationalism: 86,
    informationControl: 78,
    successionRisk: 55,
    riskTolerance: 68,
    unrest: 44,
    systems: [
      sys({
        id: "su-voevoda-claim",
        name: "R-36M2 Voevoda (claimed)",
        kind: "icbm",
        rangeKm: 16000,
        launchers: 12,
        warheads: 40,
        yieldKt: [500, 20000],
        reliability: 0.55,
        survivability: 0.18,
        disclosure: "unacknowledged",
        notes: "Claimed leftover heavies. Physical control is disputed with Moscow. A launch order from Minsk may or may not move a door in Orenburg.",
      }),
      sys({
        id: "su-tactical",
        name: "OTR-23 / tactical leftovers",
        kind: "srbm",
        rangeKm: 500,
        launchers: 24,
        warheads: 24,
        yieldKt: [10, 100],
        reliability: 0.5,
        survivability: 0.35,
        disclosure: "suspected",
        notes: "Soviet theater weapons in contested storage. Insider and theft risk is the same problem as Pakistan, with a restoration flag on it.",
      }),
      sys({
        id: "su-perimeter",
        name: "Perimeter (claimed)",
        kind: "novel",
        rangeKm: 0,
        launchers: 1,
        warheads: 0,
        yieldKt: [0, 0],
        reliability: 0.4,
        survivability: 0.7,
        disclosure: "suspected",
        notes: "Two organizations claiming Dead Hand. The danger is not that neither works. The danger is that one does.",
      }),
      sys({
        id: "su-tu95",
        name: "Tu-95 (restorationist)",
        kind: "bomber",
        rangeKm: 12000,
        launchers: 8,
        warheads: 16,
        yieldKt: [200, 50000],
        reliability: 0.45,
        survivability: 0.25,
        disclosure: "reported",
        notes: "Air-dropped Tsar-class is a reconstitution fantasy until it is not. One Tu-95V was enough in 1961.",
      }),
    ],
  });

  const CU = base("CU", "Cuba", "Cuba", 23.11, -82.37, {
    nuclear: false,
    threshold: false,
    nonstate: false,
    doctrine: "asymmetric",
    doctrineLine:
      "Not a nuclear-weapon state. Hosted Soviet warheads in 1962. Can host Russian or restorationist dual-capable systems again. The island is the aimpoint if they do.",
    stockpile: 0,
    deployed: 0,
    reserve: 0,
    retired: 0,
    secondStrike: 0,
    missileDefense: 8,
    cyber: 28,
    opacity: 55,
    intel: 34,
    leadershipStability: 62,
    nationalism: 70,
    informationControl: 72,
    riskTolerance: 42,
    legitimacy: 58,
    systems: [
      sys({
        id: "cu-host",
        name: "Hosted dual-capable (if invited)",
        kind: "srbm",
        rangeKm: 2000,
        launchers: 0,
        warheads: 0,
        yieldKt: [5, 100],
        reliability: 0.6,
        survivability: 0.2,
        disclosure: "reported",
        notes: "Zero until Moscow or Minsk parks a brigade. Then you are a 1962 target set with SBIRS watching the harbor.",
      }),
    ],
  });

  const CR = base("CR", "Transnational cartel", "Cartel", 24.81, -107.39, {
    nuclear: false,
    threshold: false,
    nonstate: true,
    doctrine: "asymmetric",
    doctrineLine:
      "Profit, not MAD. Corridors, ports, plazas, and colonels for sale. A warhead is inventory. States do not deter you with cities. They hunt you.",
    stockpile: 0,
    deployed: 0,
    reserve: 0,
    retired: 0,
    hasDevice: false,
    secondStrike: 0,
    opacity: 88,
    intel: 22,
    leadershipStability: 45,
    riskTolerance: 75,
    corruption: 92,
    unrest: 50,
    informationControl: 35,
    systems: [
      sys({
        id: "cr-stolen",
        name: "Purchased / stolen warhead",
        kind: "covert",
        rangeKm: 0,
        launchers: 0,
        warheads: 0,
        yieldKt: [0.5, 50],
        reliability: 0.4,
        survivability: 0.92,
        disclosure: "suspected",
        notes: "Cash on a Nasr, a Soviet leftover, or a Broken Arrow. PAL may hold. A plaza does not care about PAL until it does.",
      }),
      sys({
        id: "cr-dirty",
        name: "Radiological / port device",
        kind: "covert",
        rangeKm: 0,
        launchers: 0,
        warheads: 0,
        yieldKt: [0, 0],
        reliability: 0.65,
        survivability: 0.95,
        disclosure: "reported",
        notes: "Not fission. A port, a downtown, panic and markets. Distinct from a yield — treat it as such.",
      }),
    ],
  });

  const actors: Record<ActorId, Actor> = { US, RU, SU, CN, FR, UK, IN, PK, IL, KP, IR, CU, NS, CR };
  US.warning = 92;
  RU.warning = 76;
  CN.warning = 60;
  FR.warning = 64;
  UK.warning = 72;
  IN.warning = 52;
  PK.warning = 40;
  IL.warning = 66;
  KP.warning = 28;
  IR.warning = 22;
  NS.warning = 5;
  SU.warning = 44;
  CU.warning = 18;
  CR.warning = 8;

  const set = (a: ActorId, b: ActorId, h: number, t: number) => {
    actors[a].hostility[b] = h;
    actors[a].trust[b] = t;
    actors[b].hostility[a] = Math.min(100, h + 2);
    actors[b].trust[a] = t;
  };

  for (const id of ACTOR_IDS) {
    actors[id].hostility[id] = 0;
    actors[id].trust[id] = 100;
  }

  set("US", "UK", 6, 88);
  set("US", "FR", 12, 80);
  set("US", "RU", 74, 18);
  set("US", "CN", 66, 22);
  set("US", "KP", 82, 6);
  set("US", "IR", 72, 10);
  set("US", "PK", 38, 42);
  set("US", "IN", 22, 62);
  set("US", "IL", 18, 74);
  set("US", "NS", 90, 0);
  set("US", "SU", 80, 8);
  set("US", "CU", 58, 18);
  set("US", "CR", 70, 6);
  set("RU", "SU", 78, 10);
  set("RU", "CU", 22, 58);
  set("RU", "CR", 55, 12);
  set("SU", "CU", 20, 52);
  set("SU", "CN", 48, 30);
  set("SU", "NS", 72, 4);
  set("CU", "CR", 40, 28);
  set("CU", "NS", 50, 12);
  set("CR", "NS", 62, 8);
  set("CR", "PK", 44, 16);
  set("RU", "CN", 32, 55);
  set("RU", "KP", 28, 48);
  set("RU", "IR", 34, 50);
  set("RU", "UK", 70, 16);
  set("RU", "FR", 64, 22);
  set("RU", "NS", 70, 5);
  set("CN", "KP", 36, 52);
  set("CN", "IN", 58, 28);
  set("CN", "IR", 40, 48);
  set("IN", "PK", 78, 12);
  set("IL", "IR", 86, 4);
  set("IL", "NS", 92, 0);
  set("KP", "NS", 40, 15);
  set("PK", "NS", 50, 8);
  set("IR", "NS", 48, 20);

  return actors;
}
