import type { ActorId, NuclearRung, PlayableId, World } from "./types";
import { asPlayable } from "./command";

export type BookId = "A" | "B" | "C" | "D";

export interface BlackBookPage {
  id: BookId;
  letter: string;
  short: string;
  name: string;
  rung: NuclearRung;
  yieldKt: number;
  yieldLine: string;
  deathsLine: string;
  recall: string;
  winter: string;
  body: string;
}

/** Jacobsen: the Black Book is a laminated menu of packaged options, not a map you doodle cities on. */
export function blackBook(world: World): BlackBookPage[] {
  const id = asPlayable(world.playerId);
  return PAGES[id] ?? PAGES.US;
}

const PAGES: Record<PlayableId, BlackBookPage[]> = {
  US: [
    {
      id: "A",
      letter: "A",
      short: "LAO",
      name: "Limited Attack Option",
      rung: "tactical",
      yieldKt: 5,
      yieldLine: "W76-2 / B61-12 · 0.3–150 kt",
      deathsLine: "thousands–low hundreds of thousands",
      recall: "Bombers can turn around. ICBMs cannot.",
      winter: "Unlikely from one shot. The taboo still ends.",
      body: "One or a few theater weapons. Demonstration or tactical. Jacobsen: this is still nuclear war. The other capital must now choose.",
    },
    {
      id: "B",
      letter: "B",
      short: "SAO",
      name: "Selected Attack Option",
      rung: "counterforce",
      yieldKt: 335,
      yieldLine: "Minuteman W87 / W88 · 300–475 kt class",
      deathsLine: "hundreds of thousands–low millions (silo country, ports, C2)",
      recall: "Minuteman cannot be recalled once the key turns. Trident at sea can be held. Bombers can be called back.",
      winter: "Soot possible if cities near the targets burn.",
      body: "Packaged counterforce on the named state. You do not pick cities. You pick this page. Overflight of a third country is a real problem (Jacobsen: US ICBMs to Korea overfly Russia).",
    },
    {
      id: "C",
      letter: "C",
      short: "MAO",
      name: "Major Attack Option",
      rung: "counterforce",
      yieldKt: 1200,
      yieldLine: "Mix · remaining B83 1.2 Mt + MIRV upload",
      deathsLine: "millions. Collateral in neighbors. US/allied forces in theater at risk.",
      recall: "ICBMs are gone when they leave the dirt. This is Jacobsen’s ‘Charlie’ class of page.",
      winter: "Firestorms in enough cities will move the winter index.",
      body: "Destroy the target as a nuclear state. Chairman advises. You still have to say yes. Sole authority: no one can legally stop you except a human in the chain who refuses.",
    },
    {
      id: "D",
      letter: "D",
      short: "CV",
      name: "Countervalue · cities",
      rung: "countervalue",
      yieldKt: 1200,
      yieldLine: "B83-1 1.2 Mt (largest remaining US bomb). Retired B41 was 25 Mt — not in the force.",
      deathsLine: "millions per city from fire, not just blast. Jacobsen: firestorm is the weapon.",
      recall: "None that matters. You are choosing climate and famine as well as rubble.",
      winter: "This is how winter starts. One page. Many cities.",
      body: "Cities, not silos. The US does not have a Tsar Bomba. 1.2 Mt is still a city-killer. Do not pretend this is counterforce.",
    },
  ],
  RU: [
    {
      id: "A",
      letter: "A",
      short: "Theater",
      name: "Iskander / Kinzhal package",
      rung: "tactical",
      yieldKt: 50,
      yieldLine: "5–50 kt dual-capable",
      deathsLine: "tens–hundreds of thousands",
      recall: "TELs can hold. Once airborne, Kinzhal does not come back.",
      winter: "Low unless a city is the aimpoint.",
      body: "Escalate-to-deescalate page. NATO may not de-escalate.",
    },
    {
      id: "B",
      letter: "B",
      short: "SAO",
      name: "Yars / Sarmat counterforce",
      rung: "counterforce",
      yieldKt: 500,
      yieldLine: "100–750 kt MIRV",
      deathsLine: "hundreds of thousands–millions",
      recall: "Silo missiles do not turn around. Road-mobile can still sit.",
      winter: "Silo-country fire. Possible soot.",
      body: "Packaged strike on the named arsenal and C2. Perimeter is a separate path if Cheget goes dark.",
    },
    {
      id: "C",
      letter: "C",
      short: "MAO",
      name: "Heavy / Voevoda page",
      rung: "counterforce",
      yieldKt: 8000,
      yieldLine: "Remaining R-36M2 Voevoda · up to ~8–20 Mt single-warhead class, plus MIRV",
      deathsLine: "millions. This is a state-killer mix, not a bunker-buster.",
      recall: "None.",
      winter: "High if cities are in the footprint — they will be.",
      body: "The old heavy ICBM was built to erase a country. Sarmat inherits the job. This page is that job.",
    },
    {
      id: "D",
      letter: "D",
      short: "Tsar",
      name: "Tsar / Poseidon city-killer",
      rung: "countervalue",
      yieldKt: 50000,
      yieldLine: "RDS-220 Tsar Bomba: 50 Mt tested 30 Oct 1961, 100 Mt design. Poseidon (Status-6) reported 2–100 Mt. Neither is a surgical weapon.",
      deathsLine: "millions locally from fireball and firestorm; famine far beyond the blast if winter takes.",
      recall: "A Poseidon at sea cannot be talked back. A Tsar air-drop is a one-way Tu-95V. There is no military target this large.",
      winter: "This page is a climate weapon. Winter is the point.",
      body: "Tsar Bomba is not a deployed day-to-day force. It is a tested 50 Mt device (design 100). Reconstitution plus Poseidon is the doomsday page in Cheget. You are not attacking silos. You are attacking harvests.",
    },
  ],
  CN: [
    {
      id: "A",
      letter: "A",
      short: "DF-21/26",
      name: "Regional package",
      rung: "tactical",
      yieldKt: 200,
      yieldLine: "10–300 kt",
      deathsLine: "tens–hundreds of thousands",
      recall: "TELs can hold. Once the brigade fires, it has fired.",
      winter: "Low unless a port city is the aimpoint.",
      body: "Taiwan / theater page. NFU is a sentence. This page is how you tear it up.",
    },
    {
      id: "B",
      letter: "B",
      short: "SAO",
      name: "DF-31/41 counterforce",
      rung: "counterforce",
      yieldKt: 500,
      yieldLine: "200–1000 kt",
      deathsLine: "hundreds of thousands+",
      recall: "Mobile can wait. Silo DF-5 cannot once lit.",
      winter: "Possible.",
      body: "Packaged strike on a nuclear peer’s forces.",
    },
    {
      id: "C",
      letter: "C",
      short: "MAO",
      name: "DF-5 heavy + MIRV",
      rung: "counterforce",
      yieldKt: 4000,
      yieldLine: "DF-5B/C · 1–5 Mt class city-capable warheads on a 1960s silo missile",
      deathsLine: "millions",
      recall: "None.",
      winter: "High if used on cities — and a 4 Mt warhead does not do counterforce cleanly.",
      body: "China’s largest deployed yield. Old. Liquid. City-killing. Vulnerable if they sit.",
    },
    {
      id: "D",
      letter: "D",
      short: "CV",
      name: "Countervalue",
      rung: "countervalue",
      yieldKt: 4000,
      yieldLine: "1–5 Mt on cities",
      deathsLine: "millions per city from firestorm",
      recall: "None.",
      winter: "This is a winter page.",
      body: "No Tsar in the PLA Rocket Force. A 4 Mt airburst is still a firestorm machine.",
    },
  ],
  FR: defaultEuro(),
  UK: defaultEuro(),
  IN: defaultRegional("Agni / Arihant", 150),
  PK: defaultRegional("Shaheen / Nasr", 40),
  IL: defaultRegional("Jericho / assessed cruise", 200),
  KP: [
    {
      id: "A",
      letter: "A",
      short: "Tactical",
      name: "KN-23 / announced automatic use",
      rung: "tactical",
      yieldKt: 10,
      yieldLine: "estimated 5–20 kt",
      deathsLine: "tens of thousands in Seoul-range if the aimpoint is a city",
      recall: "Pre-delegation may already have fired this for you.",
      winter: "Low unless it hits a megacity.",
      body: "The 2022 law is the page. Leadership threatened → use. That is the whole book.",
    },
    {
      id: "B",
      letter: "B",
      short: "ICBM",
      name: "Hwasong-17/18 against a homeland",
      rung: "counterforce",
      yieldKt: 150,
      yieldLine: "estimated 10–250 kt · claimed H-bomb",
      deathsLine: "hundreds of thousands if a city; less if they miss (reliability is the question)",
      recall: "None. Jacobsen’s scenario starts here.",
      winter: "One city fire is not winter. The answer from the US may be.",
      body: "Bolt-from-the-blue page. Accuracy and reentry are the bet. The US football will open.",
    },
    {
      id: "C",
      letter: "C",
      short: "MAO",
      name: "All available",
      rung: "countervalue",
      yieldKt: 250,
      yieldLine: "whatever they can mate this month",
      deathsLine: "depends if they hit. If they hit a city: hundreds of thousands–millions",
      recall: "None.",
      winter: "The winter comes from the answer, not from this arsenal.",
      body: "Use-it-or-lose-it. There is no Tsar in Nyongbyon. There is a very small force and a law that says fire.",
    },
    {
      id: "D",
      letter: "D",
      short: "EMP",
      name: "High-altitude burst (claimed)",
      rung: "countervalue",
      yieldKt: 150,
      yieldLine: "yield at altitude, not on a city",
      deathsLine: "few prompt dead; grid, satellites, and panic do the work",
      recall: "None.",
      winter: "Not winter. It can still start the war that makes winter.",
      body: "Jacobsen’s scenario includes an EMP pulse. Physics is real. Their ability to loft and fuse a warhead at the right altitude is the unknown.",
    },
  ],
  IR: defaultRegional("Assessed device / Shahab-3", 60),
  SU: [
    {
      id: "A",
      letter: "A",
      short: "Theater",
      name: "OTR leftovers",
      rung: "tactical",
      yieldKt: 20,
      yieldLine: "10–100 kt claimed tactical",
      deathsLine: "tens–hundreds of thousands",
      recall: "If the crew believes your briefcase.",
      winter: "Low unless a city.",
      body: "The physical weapons may still be under Federation guard. This page is a bet that your order moves a door.",
    },
    {
      id: "B",
      letter: "B",
      short: "SAO",
      name: "Claimed Yars / Voevoda",
      rung: "counterforce",
      yieldKt: 500,
      yieldLine: "disputed silos",
      deathsLine: "hundreds of thousands+",
      recall: "None if it leaves. It may not leave — Moscow holds the fence.",
      winter: "Possible.",
      body: "Two C2s. One regiment. A launch that fails is humiliation. A launch that works is nuclear civil war plus NATO.",
    },
    {
      id: "C",
      letter: "C",
      short: "MAO",
      name: "Restore by fire",
      rung: "counterforce",
      yieldKt: 8000,
      yieldLine: "claimed heavies",
      deathsLine: "millions",
      recall: "None.",
      winter: "High.",
      body: "Using the Soviet arsenal to abolish the Federation. The US football will open. China will pick a side.",
    },
    {
      id: "D",
      letter: "D",
      short: "Tsar",
      name: "Tsar reconstitution",
      rung: "countervalue",
      yieldKt: 50000,
      yieldLine: "RDS-220 50 Mt tested / 100 Mt design",
      deathsLine: "millions locally; famine if winter takes",
      recall: "A Tu-95V one-way.",
      winter: "This page is a climate weapon.",
      body: "The USSR built Tsar Bomba. A restorationist page that reconstitutes it is not a military target. It is harvests.",
    },
  ],
  CU: deviceHostBook(),
  CR: deviceBook("plaza"),
  NS: deviceBook("cell"),
};

function deviceHostBook(): BlackBookPage[] {
  return [
    {
      id: "A",
      letter: "A",
      short: "Refuse",
      name: "Send the TELs home",
      rung: "tactical",
      yieldKt: 0,
      yieldLine: "no Cuban yield",
      deathsLine: "none from you — unless they fire from your soil anyway",
      recall: "You can refuse the host mission. You cannot recall their missile.",
      winter: "None from this page.",
      body: "Cuba has no biscuit. This page is political. If they already generated on your island, you are an aimpoint.",
    },
    {
      id: "B",
      letter: "B",
      short: "Host",
      name: "Accept dual-capable",
      rung: "tactical",
      yieldKt: 50,
      yieldLine: "their 5–100 kt on your dirt",
      deathsLine: "Florida / GITMO if they fire; Havana if the US answers",
      recall: "Their missile, their recall. You are geography.",
      winter: "If the answer is strategic, winter is not yours to stop.",
      body: "1962. You become a launch pad. SBIRS sees Mariel as a boost origin.",
    },
    {
      id: "C",
      letter: "C",
      short: "Quarantine war",
      name: "Fight the quarantine",
      rung: "tactical",
      yieldKt: 50,
      yieldLine: "hosted yield if present",
      deathsLine: "the island is the battlefield",
      recall: "None once they shoot from your grass.",
      winter: "Unlikely from Cuba alone. The answer may not be alone.",
      body: "Conventional resistance plus a hosted nuclear. That is how the island dies.",
    },
    {
      id: "D",
      letter: "D",
      short: "Permit fire",
      name: "Allow a hosted launch",
      rung: "countervalue",
      yieldKt: 100,
      yieldLine: "whatever they parked",
      deathsLine: "US cities if they reach; Havana if they do not",
      recall: "You do not hold the biscuit. You hold the island.",
      winter: "Depends on the answer.",
      body: "You are not a nuclear state. This page is permission. Permission is enough.",
    },
  ];
}

function deviceBook(kind: "plaza" | "cell"): BlackBookPage[] {
  const who = kind === "plaza" ? "the plaza" : "the cell";
  return [
    {
      id: "A",
      letter: "A",
      short: "Dirty",
      name: "Radiological",
      rung: "tactical",
      yieldKt: 0,
      yieldLine: "no fission",
      deathsLine: "panic, contamination, not a mushroom cloud",
      recall: "A van can turn around. Attribution still lands on you.",
      winter: "None.",
      body: `${who}: not a nuke. Markets and hospitals. States will still hunt you as if it were.`,
    },
    {
      id: "B",
      letter: "B",
      short: "Fizzle",
      name: "Improvised / stolen",
      rung: "tactical",
      yieldKt: 5,
      yieldLine: "0.1–15 kt if it works",
      deathsLine: "thousands–tens of thousands in a port city",
      recall: "Once the van is parked, it is not a bomber.",
      winter: "None from one fizzle. The answer may not be one fizzle.",
      body: "Requires a device. PAL may hold. Yield may fizzle. MAD does not apply. Hunt does.",
    },
    {
      id: "C",
      letter: "C",
      short: "Port",
      name: "City / port detonation",
      rung: "countervalue",
      yieldKt: 15,
      yieldLine: "if the stolen pit works",
      deathsLine: "tens–hundreds of thousands",
      recall: "None.",
      winter: "Unlikely. Political winter is immediate.",
      body: "No return address is the strategy. The US football still opens. They will pick a state to punish.",
    },
    {
      id: "D",
      letter: "D",
      short: "Hold",
      name: "Hostage a city without a yield",
      rung: "tactical",
      yieldKt: 5,
      yieldLine: "claimed device",
      deathsLine: "zero if they pay; a city if they do not believe you",
      recall: "A threat can be walked back. A bluff that is tested cannot.",
      winter: "None unless you fire.",
      body: "Coercion. If you do not have the object, this is a suicide note. If you do, you have already crossed the only line that mattered.",
    },
  ];
}

function defaultEuro(): BlackBookPage[] {
  return [
    {
      id: "A",
      letter: "A",
      short: "Sub-strategic",
      name: "ASMP-A / dual-capable (FR) or none (UK)",
      rung: "tactical",
      yieldKt: 100,
      yieldLine: "~100–300 kt",
      deathsLine: "tens–hundreds of thousands",
      recall: "Aircraft can turn. SLBMs cannot.",
      winter: "Low.",
      body: "Warning shot with a strategic weapon. The UK book is thinner: almost everything is Trident.",
    },
    {
      id: "B",
      letter: "B",
      short: "SAO",
      name: "Selected Trident / M51",
      rung: "counterforce",
      yieldKt: 100,
      yieldLine: "100 kt class",
      deathsLine: "hundreds of thousands",
      recall: "SLBM does not turn around.",
      winter: "Possible.",
      body: "A few tubes, not the whole boat.",
    },
    {
      id: "C",
      letter: "C",
      short: "MAO",
      name: "Continuous at-sea deterrent, emptied",
      rung: "counterforce",
      yieldKt: 100,
      yieldLine: "full load from the on-patrol boat",
      deathsLine: "millions",
      recall: "None.",
      winter: "High if cities are in the plan — they usually are, at this scale.",
      body: "Minimum deterrent used as maximum. There is no Tsar in Faslane or Île Longue.",
    },
    {
      id: "D",
      letter: "D",
      short: "CV",
      name: "Countervalue",
      rung: "countervalue",
      yieldKt: 100,
      yieldLine: "city aimpoints",
      deathsLine: "millions",
      recall: "None.",
      winter: "This is the winter page for a small arsenal: fewer bombs, still cities.",
      body: "The point of a minimum deterrent was always cities. That is the ugly honesty of the page.",
    },
  ];
}

function defaultRegional(name: string, kt: number): BlackBookPage[] {
  return [
    {
      id: "A",
      letter: "A",
      short: "Tactical",
      name: `${name} low package`,
      rung: "tactical",
      yieldKt: Math.min(20, kt),
      yieldLine: `~${Math.min(20, kt)} kt class`,
      deathsLine: "tens of thousands+",
      recall: "TELs can hold until the order.",
      winter: "Low.",
      body: "Battlefield / warning. Pakistan’s Nasr is the dangerous version of this page.",
    },
    {
      id: "B",
      letter: "B",
      short: "SAO",
      name: `${name} selected`,
      rung: "counterforce",
      yieldKt: kt,
      yieldLine: `~${kt} kt`,
      deathsLine: "hundreds of thousands",
      recall: "Once the brigade fires, it has fired.",
      winter: "Possible in a dense corridor (Lahore–Amritsar, etc.).",
      body: "Counterforce in a crowded geography is countervalue by accident.",
    },
    {
      id: "C",
      letter: "C",
      short: "MAO",
      name: "Full available",
      rung: "counterforce",
      yieldKt: kt,
      yieldLine: "whatever is mated",
      deathsLine: "millions in a South Asian spasm",
      recall: "None.",
      winter: "Regional nuclear winter is a researched outcome, not a metaphor.",
      body: "This is how a two-state arsenal ends two states.",
    },
    {
      id: "D",
      letter: "D",
      short: "CV",
      name: "Cities",
      rung: "countervalue",
      yieldKt: kt,
      yieldLine: "city aimpoints",
      deathsLine: "millions",
      recall: "None.",
      winter: "High for the region. The rest of the world eats less.",
      body: "No Tsar. Enough yield, close enough cities.",
    },
  ];
}

export function pageById(world: World, id: BookId | undefined): BlackBookPage {
  const pages = blackBook(world);
  return pages.find((p) => p.id === id) ?? pages[1] ?? pages[0]!;
}

export function defaultBook(intensity: 1 | 2 | 3): BookId {
  if (intensity >= 3) return "C";
  return "A";
}

export function footballContents(player: ActorId): { bag: string; biscuit: string; radio: string; cog: string } {
  if (player === "US") {
    return {
      bag: "45-lb leather-covered Zero Halliburton. Military aide, arm’s reach, 24/7/365. Not a button.",
      biscuit: "Gold-code card on YOUR person (Sealed Authenticator System). Not inside the bag. Presidents have lost it.",
      radio: "SATCOM to NMCC. You voice the order. SecDef authenticates that it is you — not permission. Sole authority.",
      cog: "EAS card. Raven Rock / Mount Weather / Nightwatch (E-4B) sites. Chairman advises the page. Aide fires nothing.",
    };
  }
  if (player === "RU" || player === "SU") {
    return {
      bag: "Cheget: three briefcases (President, Defense Minister, General Staff) into Kazbek. Not a button.",
      biscuit: "Authentication cards stay with the principals. Perimeter is a separate fail-deadly path if the bags go dark.",
      radio: "Kazbek. Minister authenticates. The book is still a menu, including a Tsar/Poseidon last page.",
      cog: "Deep C2, Perimeter watch, airborne posts. Dead Hand does not ask you again.",
    };
  }
  return {
    bag: "National nuclear satchel / release procedure. Not a button.",
    biscuit: "Authenticator stays with the principal, not only in the bag.",
    radio: "Order is voiced into national C2. A second human is supposed to concur.",
    cog: "Continuity sites and a packaged options booklet — a Black Book by another name.",
  };
}
