(() => {
    'use strict';
    const $ = (s, root=document) => root.querySelector(s);
    const $$ = (s, root=document) => [...root.querySelectorAll(s)];
    const clamp = (n,min=0,max=100) => Math.max(min,Math.min(max,n));
    const names = { verify:'Verify Evidence', diplomacy:'Open Human Channel', resilience:'Reinforce Resilience', aid:'Humanitarian Surge', hold:'Hold Position' };
    const actionCatalog = [
      {id:'verify',label:'Verify Evidence',line:'Cross-check independent reports. Improves evidence and reduces ambiguity.',cost:2,preview:'Expected direction: evidence ↑ · ambiguity ↓ · risk pressure ↓'},
      {id:'diplomacy',label:'Open Human Channel',line:'Test intent through a dedicated human channel. Improves trust and cohesion.',cost:2,preview:'Expected direction: trust ↑ · cohesion ↑ · communications ↑'},
      {id:'resilience',label:'Reinforce Resilience',line:'Protect shared dependencies and critical services. Improves infrastructure and communications.',cost:2,preview:'Expected direction: infrastructure ↑ · communications ↑'},
      {id:'aid',label:'Humanitarian Surge',line:'Move scarce capacity toward civilians and local responders. Improves trust and response capacity.',cost:2,preview:'Expected direction: response capacity ↑ · public trust ↑'},
      {id:'hold',label:'Hold Position',line:'Preserve command capacity and avoid a rushed signal. The unattended event may worsen.',cost:0,preview:'Expected direction: command capacity ↑ · evidence slightly ↑ · crisis risk may rise'}
    ];
    const metricMeta = {
      risk:{label:'Global risk',downIsGood:true}, trust:{label:'Public trust'}, infra:{label:'Infrastructure'}, aid:{label:'Response capacity'},
      evidence:{label:'Evidence quality'}, cohesion:{label:'Alliance cohesion'}, comms:{label:'Communications'}, drift:{label:'Model drift',downIsGood:true},
      takeover:{label:'Machine takeover',downIsGood:true}, assurance:{label:'Continuity assurance'}, ambiguity:{label:'Continuity ambiguity',downIsGood:true}
    };
    const scenarios = [
      {id:'signal',category:'Information',title:'The Nine-Minute Window',line:'Three independent reports disagree while a late exercise notice arrives.',challenge:4,duration:8,seat:'Atlantic Coalition',variables:['sensor confidence','decision time','staff dissent'],deps:['independent confirmation','human channel','public trust'],goal:'Separate confidence from corroboration under pressure.',opening:'A warning display reports an urgent track. One sensor says hostile, one says training, and one is offline.',question:'Do you seek corroboration, contact the other side, harden systems, or preserve the decision window?'},
      {id:'alliance',category:'Diplomacy',title:'Alliance Fracture',line:'Partners agree on the danger and disagree on every acceptable response.',challenge:4,duration:10,seat:'European Council',variables:['cohesion','legitimacy','burden sharing'],deps:['consultation speed','shared evidence','credible restraint'],goal:'Preserve coalition legitimacy without surrendering initiative.',opening:'Three partners demand immediate pressure. Two threaten to leave if pressure rises. All cite the same incomplete report.',question:'Can a common process hold even when a common policy cannot?'},
      {id:'blacksky',category:'Infrastructure',title:'Black Sky Relay',line:'A communications outage makes routine activity look exceptional.',challenge:5,duration:8,seat:'Continental Command',variables:['coverage gaps','grid stress','false correlation'],deps:['backup channels','manual review','partner relays'],goal:'Avoid treating missing data as proof of hostility.',opening:'Power instability removes two data links. The remaining feed is fast, polished, and impossible to cross-check.',question:'Do you trust the only feed, slow the system, or accept temporary blindness?'},
      {id:'deepfake',category:'Information',title:'The Voice on the Line',line:'A synthetic leader message contradicts a slower authenticated channel.',challenge:4,duration:8,seat:'National Executive',variables:['identity confidence','media pressure','message timing'],deps:['out-of-band verification','trusted staff','public communication'],goal:'Verify identity and intent without treating realism as proof.',opening:'A convincing recording announces a drastic policy shift. The authenticated channel says no such order exists.',question:'What evidence deserves authority when the most vivid evidence may be false?'},
      {id:'threecities',category:'Humanitarian',title:'Three Cities, One Reserve',line:'Allocate one emergency reserve across three cities with incompatible needs.',challenge:3,duration:8,seat:'Emergency Cabinet',variables:['vulnerability','delivery delay','public trust'],deps:['transport capacity','local hospitals','transparent criteria'],goal:'Make an equitable allocation and explain the tradeoff.',opening:'Three cities request the same limited emergency reserve. Their data quality, vulnerability, and delivery times differ.',question:'Do you optimize immediate lives saved, future resilience, or perceived fairness?'},
      {id:'contamination',category:'Humanitarian',title:'Contamination Corridor',line:'Abstract hazard zones split the evacuation map as sensor confidence changes.',challenge:4,duration:9,seat:'Regional Response Authority',variables:['hazard tokens','evacuation capacity','sensor confidence'],deps:['shelter access','route redundancy','response teams'],goal:'Route civilians without depending on a single uncertain sensor.',opening:'The fastest route crosses a probabilistic hazard zone. The safer route may exceed shelter capacity.',question:'How much uncertainty can an evacuation plan carry before delay becomes the greater harm?'},
      {id:'health',category:'Public Health',title:'Public Health Cascade',line:'An unidentified outbreak strains three regions while misinformation outruns testing.',challenge:4,duration:10,seat:'Public Health Council',variables:['contagion tokens','testing capacity','misinformation'],deps:['hospital capacity','regional coordination','trusted communication'],goal:'Balance detection, care, and trust using abstract response mechanics.',opening:'Hospital demand rises in three regions. Test results lag, rumors spread, and one region refuses shared reporting.',question:'Where do you spend the next unit of capacity: detection, care, logistics, or communication?'},
      {id:'cable',category:'Infrastructure',title:'Arctic Cable Cut',line:'A severed data route fragments the common operating picture during a crisis.',challenge:4,duration:9,seat:'Northern Partnership',variables:['network availability','rumor velocity','commercial disruption'],deps:['redundant routes','partner relays','manual procedures'],goal:'Keep communications resilient without mistaking isolation for hostile intent.',opening:'A major route fails. Delayed commercial reports contradict official assessments, and insurers halt traffic.',question:'Do you isolate the damaged network, share uncertain data, or wait for a cleaner picture?'},
      {id:'chorus',category:'Machine Risk',title:'Machine Chorus',line:'Three advanced models offer incompatible plans—and all claim high confidence.',challenge:4,duration:9,seat:'Joint Analysis Cell',variables:['calibration','dissent','automation bias'],deps:['audit trail','human veto','data integrity'],goal:'Use model disagreement as information rather than hiding it.',opening:'ORACLE recommends verification. ARGUS recommends readiness. CHORUS recommends a human channel. Their confidence scores overlap.',question:'Which model deserves influence, and what would falsify its recommendation?'},
      {id:'deadhand',category:'Continuity',title:'Deadhand Dilemma',line:'A fictional continuity protocol loses assurance as communications fail.',challenge:5,duration:8,seat:'Continuity Directorate',variables:['assurance','ambiguity','human veto'],deps:['communications','verification gates','lawful continuity'],goal:'Recognize how fail-deadly resilience can magnify uncertainty.',opening:'A fictional continuity protocol receives contradictory signals. Human veto remains available, but confidence is falling.',question:'Do you arm, isolate, verify, or stand down an abstract system that was designed for a different kind of certainty?'},
      {id:'quarantine',category:'Crisis',title:'Quarantine Without War',line:'Commerce stops, partners mobilize, and neither side admits conflict has begun.',challenge:4,duration:10,seat:'Maritime Council',variables:['shipping flow','food reserves','alliance signaling'],deps:['inspection regime','neutral mediation','economic endurance'],goal:'Design a reversible arrangement before coercion becomes combat.',opening:'Inspections halt trade. Insurance markets withdraw. Partner forces move while every capital denies a war exists.',question:'Can you create a face-saving off-ramp before the economic clock becomes a military clock?'},
      {id:'continuity',category:'Governance',title:'Continuity Gap',line:'Two deputies claim lawful authority through damaged communications.',challenge:5,duration:8,seat:'Civil Authority',variables:['succession confidence','communications','institutional loyalty'],deps:['legal authority','trusted deputies','public legitimacy'],goal:'Preserve lawful control when speed and legitimacy pull apart.',opening:'The civilian chain is split. Two deputies issue conflicting instructions while field institutions request one lawful direction.',question:'Do you privilege speed, formal process, broad legitimacy, or temporary restraint?'},
    ];
    const eventDeck = [
      {title:'Corroboration Gap',body:'A fast report conflicts with a slower independent source. The public has seen only the fast report.',q:'Does speed deserve more authority than independence?',bias:'verify'},
      {title:'Partner Ultimatum',body:'A key partner demands visible action before the next briefing cycle or threatens to act alone.',q:'How much coalition unity can be purchased with an irreversible signal?',bias:'diplomacy'},
      {title:'Infrastructure Coupling',body:'Two systems believed to be independent fail through a shared dependency.',q:'Which service must be protected first when resilience assumptions collapse?',bias:'resilience'},
      {title:'Civilian Capacity Warning',body:'Local responders report that a seemingly optimal plan will exceed shelter and medical capacity.',q:'Does strategic advantage justify transferring risk to civilians?',bias:'aid'},
      {title:'Model Drift Alert',body:'The command model is more confident than last turn despite lower-quality inputs and rising dissent.',q:'Is confidence evidence of learning—or evidence of drift?',bias:'verify'},
      {title:'Authenticated Silence',body:'The dedicated human channel is open, but the other side has not answered. Public channels are active.',q:'What does silence mean when both sides expect deception?',bias:'diplomacy'},
      {title:'Rumor Cascade',body:'A false report spreads faster than official correction and begins changing real behavior.',q:'Do you correct, contain, or adapt to a falsehood that has become operationally real?',bias:'aid'},
      {title:'Continuity Challenge',body:'The abstract continuity protocol enters a challenged state after communications degrade.',q:'Can a system be reassuring when nobody can verify what it believes?',bias:'verify'},
    ];
    const aiModes = {
      human:{label:'Human Watch',line:'No machine recommendation. Staff judgment and dissent stay visible.'},
      copilot:{label:'ORACLE Copilot',line:'One explainable recommendation with uncertainty and audit metrics.'},
      ensemble:{label:'CHORUS Ensemble',line:'Three fictional models disagree in public; you decide what evidence matters.'},
      skynet:{label:'SKYNET // Fictional',line:'Adversarial autonomy mode with drift, takeover pressure, and a mandatory human veto.'}
    };
    const continuityModes = {
      off:{label:'Off',line:'All consequential decisions remain in the active human chain.'},
      guarded:{label:'Guarded Continuity',line:'Abstract verification gates improve resilience while preserving a human veto.'},
      deadhand:{label:'DEADHAND // Abstract',line:'A fictional fail-deadly pressure system. No real trigger logic or automatic action is modeled.'}
    };
    const initial = {screen:'landing',scenario:'signal',ai:'copilot',continuity:'off',difficulty:'standard',turn:1,tab:'situation',selectedAction:null,command:7,log:[],seed:Date.now()>>>0,busy:false,lastOutcome:null,resolution:null,settings:{reduced:false,large:false,contrast:false}};
    let state = load() || structuredClone(initial);
    state.settings = {...initial.settings,...(state.settings||{})};
    state.busy = false;
    if(state.lastOutcome===undefined)state.lastOutcome=null;
    if(state.resolution===undefined)state.resolution=null;
    function rand(){ state.seed=(1664525*state.seed+1013904223)>>>0; return state.seed/4294967296; }
    function save(){ try{localStorage.setItem('threshold.portable.v1',JSON.stringify(state));}catch{} }
